### ISSUE TITLE
Function create_function() is deprecated

### ISSUE THREAD

**Issue by StuartMcD** [t1mwillis/GWCode-EE3-EE4-EE5#3]
Good ol' PHP7 and EE5. This error is being thrown when using sort, specifically line 1385

`usort($this->categories, create_function('$a,$b','return strnatcasecmp($a["'.$col_name.'"],$b["'.$col_name.'"]);'));`

I tried manually changing it as per search results directed but everything I tried just spat out more errors. ie.

`usort($this->categories, function($a, $b){'return strnatcasecmp($a["'.$col_name.'"],$b["'.$col_name.'"])';});`

Any suggestions greatly appreciated :)

**Comment by t1mwillis** [comment]
@StuartMcD can you check the recently merged PR?

**Comment by t1mwillis** [comment]
Is this resolves your issue, please close 😄

**Comment by StuartMcD** [comment]
Perfect, thx.
